apps/courses/urls.py
# -*- coding: utf-8 -*-
# ==========================================
# @Time    : 2018/3/26 下午8:58
# @Author  : Mr.Robot
# @File    : urls.py
# ==========================================

from django.urls import path, re_path
from courses import views_restful
from courses import views

urlpatterns = [
    # path("list", views_restful.CourseListRest.as_view(), name='course_list'),

    re_path(r'^list/$', views.CourseListView.as_view(), name="course_list"),
    # 课程详情页
    re_path(r'^info/(?P<course_id>\d+)/$', views.CourseInfoView.as_view(), name="course_info"),
    re_path(r'^video/(?P<lesson_id>\d+)/$', views.CourseVideoView.as_view(), name="course_video"),

    # 移动端
    re_path(r'^mobile/list/$', views_restful.CourseListRest.as_view(), name="mobile_course_list"),
    re_path(r'^mobile/info/(?P<course_id>\d+)/$', views_restful.CourseInfoRest.as_view(), name="mobile_course_info"),
    re_path(r'^mobile/video/(?P<lesson_id>\d+)/$', views_restful.CourseVideoRest.as_view(), name="mobile_course_video")
]

app_name = 'courses'

iMooc/urls.py
from django.contrib import admin
# 导入Django通用视图，以将index.html快捷地返回
from django.views.generic import TemplateView
# 开发环境下处理静态文件请求
from django.views.static import serve

from django.urls import path, include, re_path
import xadmin

from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyView
from courses.views import IndexView

from rest_framework.documentation import include_docs_urls
from iMooc.settings import MEDIA_ROOT

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    re_path('^$', IndexView.as_view(), name="index"),

    # 课程相关url配置
    re_path(r'^course/', include('courses.urls', namespace="course")),

    re_path('^login/$', LoginView.as_view(), name="login"),
    re_path('^register/$', RegisterView.as_view(), name="register"),
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    re_path(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    re_path(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    re_path(r'^modify_pwd/$', ModifyView.as_view(), name="modify_pwd"),

    # 课程机构url配置
    # re_path(r'^org/', include('orgnization.urls', namespace="org")),

    # 配置上传文件的访问处理函数
    re_path(r'media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # path('mobile/course/', include('courses.urls', namespace='courses')),
    # path('mobile/user/', include('users.urls', namespace='users')),
    # path('mobile/orgnization/', include('orgnization.urls', namespace='orgnization')),


    # rest_frame_work
    re_path('docs/', include_docs_urls("iMooc")),
    re_path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>iMooc--慕课在线学习平台</title>
    <link rel="stylesheet" href="/static/css/public.css">
    <link rel="stylesheet" href="/static/css/headerAndFooter.css">
    <!-- Swiper JS -->
    <link rel="stylesheet" href="/static/css/swiper.min.css">
    <link rel="stylesheet" href="/static/css/index.css">
</head>
<body>

<header>
    <div id="header">
        <div id="nav" style="background-color: #fff !important;">
            <div id="logo" class="logo">
                <img title="iMooc" src="/static/images/public/logo.png" onclick="window.open('./index.html', 'self')">
            </div>
            <ul id="header-nav-items">
                <li>
                    <a href="{% url 'course:course_list' %}" target="_self">免费课程</a>
                </li>
                <li>
                    <a href="//class.imooc.com" target="_self">
                        学习路径
                    </a>
                </li>
            </ul>
            <div id="search-input" style="min-width: 32px; height: 72px;">
                <div id="search-input-container">
                    <input id="search-area-input" type="text" autocomplete="off">
                </div>
            </div>
            {% if request.user.is_authenticated %}
            <div id="login-area-image-container">
                <img src="{{ request.user.image.url }}" alt="{{ request.user.username }}">
            </div>
            <div class="g-user-card">
                <div class="card-inner">
                    <div class="card-top clearfix">
                        <a href="#" class="l">
                            <img src="{{ request.user.image.url }}" alt="{{ request.user.username }}">
                        </a>
                        <div class="card-top-right-box l">
                            <a href="">
                                <span class="name text-ellipsis">{{ request.user.username }}</span>
                            </a>
                        </div>
                    </div>
                    <div class="user-center-box">
                        <ul class="clearfix">
                            <li class="l">
                                <a href="">我的课程</a>
                            </li>
                            <li class="l">
                                <a href="">个人设置</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-sets clearfix">
                        <a href="" class="l">安全退出</a>
                    </div>
                </div>
            </div>
            {% else %}
            <div id="login-area">
                <ul>
                    <li>
                        <a href="{% url 'login' %}" id="js-signin-btn">登录</a>
                    </li>
                    <li>
                        <div id="login-signup-separator">/</div>
                    </li>
                    <li>
                        <a href="{% url 'register' %}" id="js-signup-btn">注册</a>
                    </li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
</header>

<div id="swiper-courses-container">
    <!-- Swiper -->
    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for banner_course in banner_courses %}
            <div class="swiper-slide" style="background-image: url('{{ banner_course.image.url }}')!important;">
                <div class="swiper-course-label-container">
                    <div class="swiper-course-label">
                        {{ banner_course.course.name }}
                    </div>
                    <div class="swiper-course-sub-label">
                        {{ banner_course.course.desc }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
    </div>
</div>
<div id="swiper-bottom-desc">
    <div class="swiper-bottom-div">
        <div class="swiper-bottom-desc-icon1"></div>
        <div class="swiper-bottom-title">中医学公开课</div>
        <div class="swiper-bottom-subtitle">经方经,陈理陈,九州无病声</div>
    </div>
    <div class="swiper-bottom-div">
        <div class="swiper-bottom-desc-icon2"></div>
        <div class="swiper-bottom-title">针灸推拿</div>
        <div class="swiper-bottom-subtitle">治宜导引按跷，故导引按跷者，亦从中央出也</div>
    </div>
    <div class="swiper-bottom-div">
        <div class="swiper-bottom-desc-icon3"></div>
        <div class="swiper-bottom-title">中药学</div>
        <div class="swiper-bottom-subtitle">医学瑰宝，与生活息息相关</div>
    </div>
    <div class="swiper-bottom-div">
        <div class="swiper-bottom-desc-icon4"></div>
        <div class="swiper-bottom-title">方剂学</div>
        <div class="swiper-bottom-subtitle">经方经,陈理陈,九州无病声</div>
    </div>
</div>

<div id="course-new-published">
    <div class="course-new-published-container">
        <h3 class="separator-bar">
            <span class="separator-icon-l"></span>
            <em>新</em>／<em>手</em>／<em>入</em>／<em>门</em>
            <span class="separator-icon-r"></span>
        </h3>
        <div class="adsense-box" style="background: url(//img.mukewang.com/5a66a0850001c35f05670108.jpg) no-repeat center center;background-size: 100%;">
            <a href="//www.imooc.com/act/interview?mc_marking=832f2ce3bcf1a600185699f352504bea&amp;mc_channel=syzt1" data-track="xsrm-1-1" target="_blank">
                <h3 class="ellipsis">对中医药感兴趣？这些课程适合你！</h3>
                <p class="ellipsis">一大波基础课程已经抵达现场，搞定这波、对中医药有基础认识！</p>
            </a>
        </div>
        <div class="adsense-box adsense-box-right" style="background: url(//img.mukewang.com/5ab0a27300010d0905670108.jpg) no-repeat center center;background-size: 100%;">
            <a href="//www.imooc.com/topic/pyzt?mc_marking=f2c4a7f3f5299ebc266e81eed9e55ef5&amp;mc_channel=syzt2" data-track="xsrm-1-2" target="_blank">
                <h3 class="ellipsis">中医药专业新生专区</h3>
                <p class="ellipsis">浏览学习中医药高校课程，开学轻松搞定专业课！</p>
            </a>
        </div>
        {% for hot_course in hot_courses %}
        <div class="course-list-container {% if forloop.counter0|divisibleby:5 %}course-list-container-left{% endif %}">
            <a target="_blank" class="course-card" href="{% url 'course:course_info' hot_course.id %}" data-track="xsrm-1-3">
                <div class="course-card-top ">
                        <div class="img-up" style="background-image: url('{{ hot_course.image.url }}');">
                            <div class="course-label">
                                <label>{{ hot_course.tag }}</label>
                            </div>
                        </div>
                </div>
                <div class="course-card-content">
                    <h3 class="course-card-name">{{ hot_course.name }}</h3>
                    <div class="clearfix course-card-bottom">
                        <div class="course-card-info">
                            <span>职业路径</span><span>5步／33课</span><span><i class="icon-set_sns"></i>4505</span>
                        </div>
                        <div class="course-card-price">￥499.00</div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div id="course-recommend-freshman">
    <div class="course-new-published-container">
        <h3 class="separator-bar">
            <span class="separator-icon-l"></span>
            <em>新</em>／<em>手</em>／<em>入</em>／<em>门</em>
            <span class="separator-icon-r"></span>
        </h3>
        <div class="adsense-box" style="background: url(//img.mukewang.com/5a66a0850001c35f05670108.jpg) no-repeat center center;background-size: 100%;">
            <a href="//www.imooc.com/act/interview?mc_marking=832f2ce3bcf1a600185699f352504bea&amp;mc_channel=syzt1" data-track="xsrm-1-1" target="_blank">
                <h3 class="ellipsis">跳槽？面试？蠢蠢欲动？ 稳住！别慌！</h3>
                <p class="ellipsis">一大波精品面试攻略已经抵达现场，搞定这波、实力横扫全场！</p>
            </a>
        </div>
        <div class="adsense-box adsense-box-right" style="background: url(//img.mukewang.com/5ab0a27300010d0905670108.jpg) no-repeat center center;background-size: 100%;">
            <a href="//www.imooc.com/topic/pyzt?mc_marking=f2c4a7f3f5299ebc266e81eed9e55ef5&amp;mc_channel=syzt2" data-track="xsrm-1-2" target="_blank">
                <h3 class="ellipsis">未来大趋势，人工智能首选Python语言！</h3>
                <p class="ellipsis">从菜鸟到Pythoner，最新最全的学习路线，让你更专业！</p>
            </a>
        </div>
        {% for fresh_man_course in fresh_man_courses %}
        <div class="course-list-container {% if forloop.counter0|divisibleby:5 %}course-list-container-left{% endif %}">
            <a target="_blank" class="course-card" href="{% url 'course:course_info' fresh_man_course.id %}" data-track="xsrm-1-3">
                <div class="course-card-top ">
                    <div class="img-up" style="background-image: url('{{ fresh_man_course.image.url }}');">
                        <div class="course-label">
                            <label>{{ fresh_man_course.tag }}</label>
                        </div>
                    </div>
                </div>
                <div class="course-card-content">
                    <h3 class="course-card-name">{{ fresh_man_course.name }}</h3>
                    <div class="clearfix course-card-bottom">
                        <div class="course-card-info">
                            <span>职业路径</span><span>5步／33课</span><span><i class="icon-set_sns"></i>4505</span>
                        </div>
                        <div class="course-card-price">￥499.00</div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<footer>
    <div class="footer-container">
        <div class="footer-wrap idx-width">
            <div class="footer-sns clearfix">
                <div class="l">
                    <a href="javascript:void(0);" class="footer-sns-weixin" target="_blank" title="微信">
                        <i class="footer-sns-weixin-expand"></i>
                    </a>
                    <p>官方公众号</p>
                </div>
                <div class="l">
                    <a href="http://weibo.com/u/3306361973" class="footer-sns-weibo hide-text" target="_blank" title="新浪微博">
                    </a>
                    <p>官方微博</p>
                </div>
            </div>
        </div>
        <div class="footer-link">
            <!-- <a href="/about/us" target="_blank" title="关于我们">关于我们</a> -->
            <a href="/about/cooperate" target="_blank" title="企业合作">企业合作</a>
            <a href="/about/job" target="_blank" title="人才招聘">人才招聘</a>
            <a href="/about/contact" target="_blank" title="联系我们">联系我们</a>
            <a href="/about/recruit" target="_blank" title="讲师招募">讲师招募</a>
            <a href="/about/faq" target="_blank" title="常见问题">常见问题</a>
            <a href="/user/feedback" target="_blank" title="意见反馈">意见反馈</a>
            <a href="http://daxue.imooc.com/" target="_blank">慕课大学</a>
            <a href="/about/friendly" target="_blank" title="友情链接">友情链接</a>
        </div>
        <div class="footer-copyright">
            <p>©&nbsp;2018&nbsp;中源团队&nbsp;&nbsp;南京中医药大学 信息技术学院</p>
        </div>
    </div>
</footer>

<script src="/static/js/public/jquery-3.3.1.min.js"></script>
<script src="/static/js/index/swiper.min.js"></script>
<script src="/static/js/public/headerAndFooter.js"></script>
<script>
    var swiper = new Swiper('.swiper-container', {
        spaceBetween: 30,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
    });
</script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/css/public.css">
    <link rel="stylesheet" href="../static/css/headerAndFooter.css">
    <link rel="stylesheet" href="../static/css/login.css">
    <title>登录/注册</title>
</head>

<body>
<header>
    <div id="header">
        <div id="nav" style="background-color: #fff !important;">
            <div id="logo" class="logo">
                <img title="iMooc" src="../static/images/public/logo.png" onclick="window.open('./index.html', 'self')">
            </div>
            <ul id="header-nav-items">
                <li>
                    <a href="/course/list" target="_self">免费课程</a>
                </li>
                <li>
                    <a href="//class.imooc.com" target="_self">
                        学习路径
                    </a>
                </li>
            </ul>
            <div id="search-input" style="min-width: 32px; height: 72px;">
                <div id="search-input-container">
                    <input id="search-area-input" type="text" autocomplete="off">
                </div>
            </div>
            <div id="login-area">
                <ul>
                    <li>
                        <a href="#" id="js-signin-btn">登录</a>
                    </li>
                    <li>
                        <div id="login-signup-separator">/</div>
                    </li>
                    <li>
                        <a href="#" id="js-signup-btn">注册</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

<!--登录/注册框-->
<div id="login-background-container">
    <div id="login-background">
    </div>
    <div class="login-box">
        <div class="lb-header">
            <a href="#" class="active" id="login-box-link">登录</a>
            <a href="#" id="signup-box-link">注册</a>
        </div>
        <form class="email-login" action="{% url 'login' %}" method="post">
            <div class="u-form-group">
                <input name="username" type="email" placeholder="邮箱"/>
            </div>
            <div class="u-form-group">
                <input name="password" type="password" placeholder="密码"/>
            </div>
            <div class="u-form-group" >
                <button type="submit">登录</button>
            </div>
            <div class="fast-login-container">
                <div id="fast-login-weixin" class="fast-login" onclick="window.open('', '_self')"></div>
                <div id="fast-login-QQ" class="fast-login" onclick="window.open('', '_self')"></div>
            </div>
            <div class="u-form-group">
                <a href="#" class="forgot-password">忘记密码?</a>
            </div>
            {% csrf_token %}
        </form>
        <form class="email-signup" action="{% url 'register' %}" method="post">
            <div class="u-form-group">
                <input type="email" placeholder="邮箱"/>
            </div>
            <div class="u-form-group">
                <input type="password" placeholder="密码"/>
            </div>
            <div class="u-form-group">
                <input type="password" placeholder="确认密码"/>
            </div>
            <div class="u-form-group">
                <button type="submit">注册</button>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

<footer>
    <div class="footer-container">
        <div class="footer-wrap idx-width">
            <div class="footer-sns clearfix">
                <div class="l">
                    <a href="javascript:void(0);" class="footer-sns-weixin" target="_blank" title="微信">
                        <i class="footer-sns-weixin-expand"></i>
                    </a>
                    <p>官方公众号</p>
                </div>
                <div class="l">
                    <a href="http://weibo.com/u/3306361973" class="footer-sns-weibo hide-text" target="_blank" title="新浪微博">
                    </a>
                    <p>官方微博</p>
                </div>
            </div>
        </div>
        <div class="footer-link">
            <!-- <a href="/about/us" target="_blank" title="关于我们">关于我们</a> -->
            <a href="/about/cooperate" target="_blank" title="企业合作">企业合作</a>
            <a href="/about/job" target="_blank" title="人才招聘">人才招聘</a>
            <a href="/about/contact" target="_blank" title="联系我们">联系我们</a>
            <a href="/about/recruit" target="_blank" title="讲师招募">讲师招募</a>
            <a href="/about/faq" target="_blank" title="常见问题">常见问题</a>
            <a href="/user/feedback" target="_blank" title="意见反馈">意见反馈</a>
            <a href="http://daxue.imooc.com/" target="_blank">慕课大学</a>
            <a href="/about/friendly" target="_blank" title="友情链接">友情链接</a>
        </div>
        <div class="footer-copyright">
            <p>©&nbsp;2018&nbsp;中源团队&nbsp;&nbsp;南京中医药大学 信息技术学院</p>
        </div>
    </div>
</footer>
</body>
<script type="text/javascript" src="../static/js/public/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $(".email-signup").hide();
        $("#signup-box-link").click(function(){
            $(".email-login").fadeOut(100);
            $(".email-signup").delay(100).fadeIn(100);
            $("#login-box-link").removeClass("active");
            $("#signup-box-link").addClass("active");
        });
        $("#login-box-link").click(function(){
            $(".email-login").delay(100).fadeIn(100);;
            $(".email-signup").fadeOut(100);
            $("#login-box-link").addClass("active");
            $("#signup-box-link").removeClass("active");
        });
    });
</script>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/css/public.css">
    <link rel="stylesheet" href="../static/css/headerAndFooter.css">
    <link rel="stylesheet" href="../static/css/login.css">
    <title>登录/注册</title>
</head>

<body>
<header>
    <div id="header">
        <div id="nav" style="background-color: #fff !important;">
            <div id="logo" class="logo">
                <img title="iMooc" src="../static/images/public/logo.png" onclick="window.open('./index.html', 'self')">
            </div>
            <ul id="header-nav-items">
                <li>
                    <a href="/course/list" target="_self">免费课程</a>
                </li>
                <li>
                    <a href="//class.imooc.com" target="_self">
                        学习路径
                    </a>
                </li>
            </ul>
            <div id="search-input" style="min-width: 32px; height: 72px;">
                <div id="search-input-container">
                    <input id="search-area-input" type="text" autocomplete="off">
                </div>
            </div>
            <div id="login-area">
                <ul>
                    <li>
                        <a href="#" id="js-signin-btn">登录</a>
                    </li>
                    <li>
                        <div id="login-signup-separator">/</div>
                    </li>
                    <li>
                        <a href="#" id="js-signup-btn">注册</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

<!--登录/注册框-->
<div id="login-background-container">
    <div id="login-background">
    </div>
    <div class="login-box">
        <div class="lb-header">
            <a href="#" class="" id="login-box-link">登录</a>
            <a href="#" class="active" id="signup-box-link">注册</a>
        </div>
        <form class="email-login" action="{% url 'login' %}" method="post">
            <div class="u-form-group">
                <input name="email" type="email" placeholder="邮箱"/>
            </div>
            <div class="u-form-group">
                <input name="password" type="password" placeholder="密码"/>
            </div>
            <div class="u-form-group" >
                <button type="button">登录</button>
            </div>
            <div class="fast-login-container">
                <div id="fast-login-weixin" class="fast-login" onclick="window.open('', '_self')"></div>
                <div id="fast-login-QQ" class="fast-login" onclick="window.open('', '_self')"></div>
            </div>
            <div class="u-form-group">
                <a href="#" class="forgot-password">忘记密码?</a>
            </div>
            {% csrf_token %}
        </form>
        <form class="email-signup" action="{% url 'register' %}" method="post">
            <div class="u-form-group">
                <input name="email" type="email" placeholder="邮箱"/>
            </div>
            <div class="u-form-group">
                <input name="password" type="password" placeholder="密码"/>
            </div>
            <div class="u-form-group">
                <input name="re-password" type="password" placeholder="确认密码"/>
            </div>
            <div class="form-group captcha1 {% if register_form.errors.captcha %}errorput{% endif %}">
                {{ register_form.captcha }}
            </div>
            <div class="error btns" id="jsEmailTips">
                {% for key,error in register_form.errors.items %}{{ error }}{% endfor%}{{ message }}
            </div>
            <div class="u-form-group">
                <button type="submit">注册</button>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

<footer>
    <div class="footer-container">
        <div class="footer-wrap idx-width">
            <div class="footer-sns clearfix">
                <div class="l">
                    <a href="javascript:void(0);" class="footer-sns-weixin" target="_blank" title="微信">
                        <i class="footer-sns-weixin-expand"></i>
                    </a>
                    <p>官方公众号</p>
                </div>
                <div class="l">
                    <a href="http://weibo.com/u/3306361973" class="footer-sns-weibo hide-text" target="_blank" title="新浪微博">
                    </a>
                    <p>官方微博</p>
                </div>
            </div>
        </div>
        <div class="footer-link">
            <!-- <a href="/about/us" target="_blank" title="关于我们">关于我们</a> -->
            <a href="/about/cooperate" target="_blank" title="企业合作">企业合作</a>
            <a href="/about/job" target="_blank" title="人才招聘">人才招聘</a>
            <a href="/about/contact" target="_blank" title="联系我们">联系我们</a>
            <a href="/about/recruit" target="_blank" title="讲师招募">讲师招募</a>
            <a href="/about/faq" target="_blank" title="常见问题">常见问题</a>
            <a href="/user/feedback" target="_blank" title="意见反馈">意见反馈</a>
            <a href="http://daxue.imooc.com/" target="_blank">慕课大学</a>
            <a href="/about/friendly" target="_blank" title="友情链接">友情链接</a>
        </div>
        <div class="footer-copyright">
            <p>©&nbsp;2018&nbsp;中源团队&nbsp;&nbsp;南京中医药大学 信息技术学院</p>
        </div>
    </div>
</footer>
</body>
<script type="text/javascript" src="../static/js/public/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $(".email-login").hide();
        $("#signup-box-link").click(function(){
            $(".email-login").fadeOut(100);
            $(".email-signup").delay(100).fadeIn(100);
            $("#login-box-link").removeClass("active");
            $("#signup-box-link").addClass("active");
        });
        $("#login-box-link").click(function(){
            $(".email-login").delay(100).fadeIn(100);;
            $(".email-signup").fadeOut(100);
            $("#login-box-link").addClass("active");
            $("#signup-box-link").removeClass("active");
        });
        $("button").click(function(){
            window.open("index.html","_self")
        });
        $("#id_captcha_1").attr("placeholder", "验证码")
    });
</script>
</html>